# Generated by Django 5.0.6 on 2025-07-01 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0003_talhao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Insumo')),
                ('tipo', models.CharField(choices=[('Fertilizante', 'Fertilizante'), ('Agroquímico', 'Agroquímico'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo de Insumo')),
                ('unidade_medida', models.CharField(max_length=20, verbose_name='Unidade de Medida')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Agroquimico',
            fields=[
                ('insumo_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insumos.insumo')),
                ('classe_toxicologica', models.CharField(max_length=50, verbose_name='Classe Toxicológica')),
                ('registro_ministerio', models.CharField(max_length=100, unique=True, verbose_name='Registro no Ministério')),
            ],
            options={
                'verbose_name': 'Agroquímico',
                'verbose_name_plural': 'Agroquímicos',
            },
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('insumo_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='insumos.insumo')),
                ('composicao', models.TextField(verbose_name='Composição')),
                ('garantia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Garantia')),
            ],
            options={
                'verbose_name': 'Fertilizante',
                'verbose_name_plural': 'Fertilizantes',
            },
        ),
        migrations.CreateModel(
            name='EstoqueInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='insumos.insumo')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques_insumo', to='produtores.propriedade')),
            ],
            options={
                'verbose_name': 'Estoque de Insumo',
                'verbose_name_plural': 'Estoques de Insumos',
                'unique_together': {('insumo', 'propriedade')},
            },
        ),
    ]
