# Generated by Django 5.0.6 on 2025-07-02 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atividades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True, verbose_name='Código do Lote')),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade (kg)')),
                ('data_formacao', models.DateField(auto_now_add=True, verbose_name='Data de Formação do Lote')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('colheita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='atividades.colheita')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
            },
        ),
        migrations.CreateModel(
            name='Processamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_processamento', models.CharField(choices=[('Via Seca', 'Via Seca'), ('Via Úmida', 'Via Úmida'), ('Descascamento', 'Descascamento'), ('Torra', 'Torra'), ('Moagem', 'Moagem'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo de Processamento')),
                ('data_processamento', models.DateField(verbose_name='Data de Processamento')),
                ('quantidade_processada_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Processada (kg)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processamentos', to='producao.lote')),
            ],
            options={
                'verbose_name': 'Processamento',
                'verbose_name_plural': 'Processamentos',
            },
        ),
    ]
