# Generated by Django 5.0.6 on 2025-07-01 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtores', '0003_talhao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(choices=[('Plantio', 'Plantio'), ('Colheita', 'Colheita'), ('Adubacao', 'Adubação'), ('Pulverizacao', 'Pulverização'), ('Irrigacao', 'Irrigação'), ('Poda', 'Poda'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo de Atividade')),
                ('data_atividade', models.DateField(verbose_name='Data da Atividade')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo (R$)')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='produtores.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-data_atividade'],
            },
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colheita', models.DateField(verbose_name='Data da Colheita')),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade Colhida (kg)')),
                ('tipo_cafe', models.CharField(max_length=100, verbose_name='Tipo de Café Colhido')),
                ('qualidade_colheita', models.CharField(blank=True, max_length=50, null=True, verbose_name='Qualidade da Colheita')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colheitas', to='produtores.talhao', verbose_name='Talhão')),
            ],
            options={
                'verbose_name': 'Colheita',
                'verbose_name_plural': 'Colheitas',
                'ordering': ['-data_colheita'],
            },
        ),
    ]
