# Generated by Django 5.0.6 on 2025-07-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Produtor')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('identificacao', models.CharField(max_length=14, unique=True, verbose_name='CPF/CNPJ')),
                ('sexo', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sexo')),
                ('endereco_rua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('endereco_numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('endereco_bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('endereco_municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('endereco_estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('status', models.CharField(default='Ativo', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtores',
            },
        ),
    ]
