# Generated by Django 5.0.6 on 2025-07-01 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtor',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10, null=True, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='produtor',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Propriedade')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código da Propriedade')),
                ('area_total_ha', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área Total (ha)')),
                ('endereco_rua', models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua')),
                ('endereco_numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('endereco_bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('endereco_municipio', models.CharField(max_length=100, verbose_name='Município')),
                ('endereco_estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('produtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propriedades', to='produtores.produtor')),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
            },
        ),
    ]
