# Generated by Django 5.0.6 on 2025-07-01 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtores', '0002_alter_produtor_sexo_alter_produtor_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talhao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Talhão')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código do Talhão')),
                ('area_ha', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área (ha)')),
                ('tipo_cultivo', models.CharField(max_length=100, verbose_name='Tipo de Cultivo')),
                ('data_plantio', models.DateField(blank=True, null=True, verbose_name='Data de Plantio')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talhoes', to='produtores.propriedade')),
            ],
            options={
                'verbose_name': 'Talhão',
                'verbose_name_plural': 'Talhões',
            },
        ),
    ]
