# Generated by Django 5.0.6 on 2025-07-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producao', '0001_initial'),
        ('produtores', '0003_talhao'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoRastreabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('Colheita', 'Colheita'), ('Processamento', 'Processamento'), ('Armazenamento', 'Armazenamento'), ('Transporte', 'Transporte'), ('Comercializacao', 'Comercialização'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo de Evento')),
                ('data_evento', models.DateTimeField(verbose_name='Data do Evento')),
                ('local', models.CharField(max_length=255, verbose_name='Local do Evento')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Responsável')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_rastreabilidade', to='producao.lote')),
            ],
            options={
                'verbose_name': 'Evento de Rastreabilidade',
                'verbose_name_plural': 'Eventos de Rastreabilidade',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='MedicaoIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_indicador', models.CharField(choices=[('Temperatura', 'Temperatura'), ('Umidade', 'Umidade'), ('pH Solo', 'pH do Solo'), ('Nutrientes Solo', 'Nutrientes do Solo'), ('Produtividade', 'Produtividade'), ('Outro', 'Outro')], max_length=50, verbose_name='Tipo de Indicador')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('unidade_medida', models.CharField(max_length=20, verbose_name='Unidade de Medida')),
                ('data_medicao', models.DateTimeField(verbose_name='Data da Medição')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('talhao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='produtores.talhao')),
            ],
            options={
                'verbose_name': 'Medição de Indicador',
                'verbose_name_plural': 'Medições de Indicadores',
                'ordering': ['-data_medicao'],
            },
        ),
    ]
